// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	SearchTerms          []string `protobuf:"bytes,1,rep,name=searchTerms,proto3" json:"searchTerms,omitempty"`
	Documents            []string `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetSearchTerms() []string {
	if m != nil {
		return m.SearchTerms
	}
	return nil
}

func (m *Task) GetDocuments() []string {
	if m != nil {
		return m.Documents
	}
	return nil
}

type DocumentData struct {
	TermToFrequency      map[string]float64 `protobuf:"bytes,1,rep,name=termToFrequency,proto3" json:"termToFrequency,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DocumentData) Reset()         { *m = DocumentData{} }
func (m *DocumentData) String() string { return proto.CompactTextString(m) }
func (*DocumentData) ProtoMessage()    {}
func (*DocumentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}
func (m *DocumentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentData.Unmarshal(m, b)
}
func (m *DocumentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentData.Marshal(b, m, deterministic)
}
func (m *DocumentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentData.Merge(m, src)
}
func (m *DocumentData) XXX_Size() int {
	return xxx_messageInfo_DocumentData.Size(m)
}
func (m *DocumentData) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentData.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentData proto.InternalMessageInfo

func (m *DocumentData) GetTermToFrequency() map[string]float64 {
	if m != nil {
		return m.TermToFrequency
	}
	return nil
}

type Result struct {
	DocumentToDocumentData map[string]*DocumentData `protobuf:"bytes,1,rep,name=documentToDocumentData,proto3" json:"documentToDocumentData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetDocumentToDocumentData() map[string]*DocumentData {
	if m != nil {
		return m.DocumentToDocumentData
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "model.Task")
	proto.RegisterType((*DocumentData)(nil), "model.DocumentData")
	proto.RegisterMapType((map[string]float64)(nil), "model.DocumentData.TermToFrequencyEntry")
	proto.RegisterType((*Result)(nil), "model.Result")
	proto.RegisterMapType((map[string]*DocumentData)(nil), "model.Result.DocumentToDocumentDataEntry")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xdc, 0xb8, 0x58, 0x42,
	0x12, 0x8b, 0xb3, 0x85, 0x14, 0xb8, 0xb8, 0x8b, 0x53, 0x13, 0x8b, 0x92, 0x33, 0x42, 0x52, 0x8b,
	0x72, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0x90, 0x85, 0x84, 0x64, 0xb8, 0x38, 0x53,
	0xf2, 0x93, 0x4b, 0x73, 0x53, 0xf3, 0x4a, 0x8a, 0x25, 0x98, 0xc0, 0xf2, 0x08, 0x01, 0xa5, 0x65,
	0x8c, 0x5c, 0x3c, 0x2e, 0x50, 0x9e, 0x4b, 0x62, 0x49, 0xa2, 0x50, 0x10, 0x17, 0x7f, 0x49, 0x6a,
	0x51, 0x6e, 0x48, 0xbe, 0x5b, 0x51, 0x6a, 0x61, 0x69, 0x6a, 0x5e, 0x72, 0x25, 0xd8, 0x50, 0x6e,
	0x23, 0x0d, 0x3d, 0x88, 0x33, 0x90, 0x55, 0xeb, 0x85, 0xa0, 0x2a, 0x75, 0xcd, 0x2b, 0x29, 0xaa,
	0x0c, 0x42, 0x37, 0x40, 0xca, 0x89, 0x4b, 0x04, 0x9b, 0x42, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0x54,
	0x90, 0xf9, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69,
	0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x84, 0x63, 0xc5, 0x64, 0xc1, 0xa8, 0x74, 0x9a,
	0x91, 0x8b, 0x2d, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x44, 0x28, 0x91, 0x4b, 0x0c, 0xe6, 0x81, 0x90,
	0x7c, 0x64, 0xe7, 0x40, 0x5d, 0xaa, 0x09, 0x75, 0x29, 0x44, 0x39, 0xdc, 0xc1, 0xa8, 0x6a, 0x21,
	0x4e, 0xc5, 0x61, 0x90, 0x54, 0x1c, 0x97, 0x34, 0x1e, 0x6d, 0x58, 0x1c, 0xae, 0x89, 0xec, 0x70,
	0x6e, 0x23, 0x61, 0x2c, 0x81, 0x85, 0xe4, 0x9b, 0x24, 0x36, 0x70, 0x64, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x1c, 0x7c, 0xc7, 0x6b, 0xdb, 0x01, 0x00, 0x00,
}
